#!/usr/bin/php

<?php

/**
 *      APHID Command Line API.
 * 
 *      Developed by @wtfribley. 
 */

// Define the Base Path

define('PATH', pathinfo(__FILE__, PATHINFO_DIRNAME) . '/');

// Block Direct Access

define("PRIVATE", true);

// Bootstrap

require PATH . 'app/run.php';

?>